// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIj38tIL6SJMLGMh6gXVzA7CA1qLMU5vc',
    appId: '1:1007218222332:web:0af86af57b8a32f0746379',
    messagingSenderId: '1007218222332',
    projectId: 'blood-bank-2d309',
    authDomain: 'blood-bank-2d309.firebaseapp.com',
    storageBucket: 'blood-bank-2d309.firebasestorage.app',
    measurementId: 'G-7XKG89GLKT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzYtN6MtYfz4bzOqq6_w0xvdvmNo4-2Rk',
    appId: '1:1007218222332:android:4960a265e9efecea746379',
    messagingSenderId: '1007218222332',
    projectId: 'blood-bank-2d309',
    storageBucket: 'blood-bank-2d309.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAncV8NKuci5wy-tY9KTvUCBXk8hJQ0HLY',
    appId: '1:1007218222332:ios:3aba2ca73aacba0b746379',
    messagingSenderId: '1007218222332',
    projectId: 'blood-bank-2d309',
    storageBucket: 'blood-bank-2d309.firebasestorage.app',
    iosBundleId: 'com.example.graduationProject',
  );
}
